" .vim/vimrc
" 
"   The commands in the file are
"   run as if in vim command mode.
"   
"   First /etc/vimrc is sourced, which should first sources
"   your distribution's vim-package related configuration
"   files and then your system admins "helpful" system-wide
"   configuration changes.  Then this file is sourced.
"
"   Warning: If neither ~/.vimrc nor ~/.vim/vimrc exist,
"   vim will source a "default.vim" file (unless the SA put
"   let skip_defaults_vim=1 in /etc/vimrc).  This can
"   very well overide behavior in /etc/vimrc!  Not knowing
"   about the existence of this default configuration file
"   can be very confusing to new and intermediate vim users.
"   Simply creating an empty ~/.vimrc file can radically
"   change vim behavior.

" Setup the Vundle plugin manager
"
" Initially you will need to bootstrap the Vundle infrastructure
" by manually cloning it into the right place:
"
"   $ git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
"
" and then from within vim run
"
"   :PluginInstall
"
set nocompatible    " be iMproved, required by Vundle
filetype off        " required by Vundle

" Set the runtime path to include Vundle
set rtp+=~/.vim/bundle/Vundle.vim

" Initialize Vundle
call vundle#begin()
" Let Vundle manage Vundle, required by Vundle
Plugin 'VundleVim/Vundle.vim'

" GitHub plugins for Vundle to manage:

"   Extend */# functionality while in visual mode
Plugin 'nelstrom/vim-visual-star-search'

"   Provide syntax checking for a variety of languages
Plugin 'vim-syntastic/syntastic'

"   Provide Rust file detection, syntax highlighting,
"   formatting, syntastic integration, and more.
Plugin 'rust-lang/rust.vim'

call vundle#end()
filetype plugin indent on   " required by Vundle
" End setup for the Vundle plugin manager

" Configure new user settings for Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Turn on and configure syntaxic color highlighting
syntax on
" To turn off colors, use ":syntax off"
"
" Set the default color scheme
colorscheme elflord
"
" To select a different color scheme while in vim,
" tab through
"
"   :colorscheme blue
"
" first to get the command, then to get the color scheme.
"
" Example of a color scheme that does not come with Vim,
"
"   From https://github.com/tomasr/molokai, put the
"   colorscheme file here: ~/.vim/color/molokai.vim
"
"   Customizations come before :colorscheme command.
"
" let g:molokai_original = 1
" colorscheme molokai

" Set default encoding
"   
" Use utf-8 (I am a utf-8 fanboy)
set encoding=utf-8
set fileencoding=utf-8

" Set the default language to US English for spell checking.
set spelllang=en_us
"
" To turn on spellcheck         :set spell
" To turn it off spellchecking  :set nospell

" Set default tabstops and replace tabs with spaces
set tabstop=4
set shiftwidth=4
set expandtab

" Don't configure vim to use mouse
set mouse=
"
" Sometimes it useful to configure the mouse on
" the fly in vim, but usually I prefer the terminal
" emulator to receive mouse events.  Works better
" with my "sloppy focus follows mouse" style of
" GUI-CLI integration.
" 
" See :help mouse-using to configure the mouse
"   When enabled, use <shift>-clicks to send mouse
"   events to the terminal instead of vim.
"
" For convienence in :help windows, from within vim,
"   :set mouse=a
