#!/bin/bash
#
# Install Bash Environment & other config. files into home directory
#
# To use:
#    1. Make sure you know what you are doing,
#    2. Unless you are me, use this as a
#       template for your own version.
#    3. Does not automatically install the 
#       X-Windows files, they are for one
#       specific Arch Linux computer.
#    4. Run from the BashEnvConf directory.
#

DOT_FILES='
    .bashrc
    .bash_profile
    .bash_init
    .bash_logout
    .inputrc
'

### Back up existing dot-files in case things go wrong
for File in $DOT_FILES
do
    diff ~/"$File" ~/"${File}.old" &>/dev/null && continue
    [[ ! -f ~/$File ]] || cp ~/"$File" ~/"${File}.old" || { echo "Error: Failed to backup previous ~/$File" >&2; exit 1; }
done

### Install home directory dot-files
for File in $DOT_FILES
do
    cp "$File" ~ || echo "Warning: Failed to install ~/$File" >&2
    chmod u=rw,g=r,o= "$File" || "Warning: Failed to set permissions on ~/$File to 750" >&2
done

### Make sure ~/catch is there for the toSystem() shell function
[[ -d ~/catch ]] || mkdir ~/catch || echo 'Warning: Failed to create ~/catch, do so manually.' >&2

### Install vimrc
[[ -f ~/.vimrc ]] && mv ~/.vimrc ~/.vimrc_old && echo 'Warning: Move existing ~/.vimrc => ~/.vimrcr_old' >&2
[[ -d ~/.vim ]] || mkdir ~/.vim || echo 'Warning: Failed to create ~/.vim, punting on installing ~/.vim/`vimrc' >&2
[[ -f ~/.vim/vimrc ]] && mv ~/.vim/vimrc ~/.vim/vimrc_old || echo 'Warning: Failed making backup of old ~/.vim/vimrc' >&2
[[ -d ~/.vim ]] && cp ./.vim/vimrc ~/.vim || echo 'Warning: Failed to install ~/.vim/vimrc' >&2
[[ -f ~/.vim/vimrc ]] && chmod u=rw,g=r,o= ~/.vim/vimrc || echo 'Warning: Failed to set permissions on ~/vim/vimrc to 640' >&2 

### Create ~/bin directory if necessary
[[ -d ~/bin ]] || mkdir ~/bin || { echo 'Error: Failed to create ~/bin' >&2; exit 1; }
chmod u=rwx,g=rx,o= ~/bin || echo 'Warning: Failed to set permissions on ~/bin to 750' >&2 

BIN_SCRIPTS='
    digpath
    g3ScaleBG
    g3SetBG
    monitor
    path
    pathtrim
    rt
    spin
    viewJarManifest
'

### Install ~/bin scripts
for File in $BIN_SCRIPTS
do
    cp bin/"$File" ~/bin || echo "Warning: Failed to install ~/bin/$File" >&2
    chmod u=rwx,g=rx,o= ~/bin/"$File" || "Warning: Failed to set permissions on /bin/$File to 750" >&2
done

# Setup Symlinks for MATLAB
# Find where MATLAB is installed:
if [[ -d ~/opt/MATLAB ]]; then
    MATLAB_INSTALL_DIR=~/opt/MATLAB
elif [[ -d ~/local/MATLAB ]]; then
    MATLAB_INSTALL_DIR=~/local/MATLAB
elif [[ -d /opt/MATLAB ]]; then
    MATLAB_INSTALL_DIR=/usr/local/MATLAB
elif [[ -d /usr/local/MATLAB ]]; then
    MATLAB_INSTALL_DIR=/usr/local/MATLAB
else
    MATLAB_INSTALL_DIR=""
fi

if [[ -d $MATLAB_INSTALL_DIR ]]
then
    #Find latest version of MATLAB and create symlinks
    MATLAB_BIN=$MATLAB_INSTALL_DIR/$(for Rdir in "$MATLAB_INSTALL_DIR"/R*
                                     do
                                         echo "${Rdir##*/}"
                                     done | sort | tail -1)/bin
    rm -f ~/bin/{matlab,mex}
    ln -s "$MATLAB_BIN"/{matlab,mex} ~/bin 2> /dev/null
fi
