name: pythag-triples
version: 0.4.0
synopsis: Pythagorean triple CLI generation program
category: Example
author: Geoffrey Scheller
maintainer: Geoffrey Scheller <geoffrey@scheller.com>
copyright: (c) 2016-2020 Geoffrey R Scheller
license: BSD3
license-file: LICENSE
extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - split

source-dirs:
  - src

library:
  exposed-modules: PythagTriples
  ghc-options: -Wall

executables:
  pythagTriples:
    source-dirs: bin
    main: pythagTriples.hs
    ghc-options: -Wall -dynamic -threaded -rtsopts -with-rtsopts=-N

tests:
  spec:
    source-dirs: test
    main: spec.hs
    ghc-options: -Wall -dynamic -threaded -rtsopts -with-rtsopts=-N
