#!/bin/bash
#
# Installs my Unix/Linux environment into my home directory.

export DOT_FILES BIN_SCRIPTS 

###
### First install the bash setup files.
DOT_FILES='
    .bashrc
    .bash_profile
    .bash_logout
    .inputrc
    .wgetrc
'

cp -f $DOT_FILES ~
(cd ~; chmod 440 $DOT_FILES)

###
### Make sure ~/catch and ~/pitch are there
[[ -d ~/catch ]] || mkdir ~/catch
[[ -d ~/pitch ]] || mkdir ~/pitch

###
### Install vimrc
[[ ! -f ~/.vimrc ]] || rm -f ~/.vimrc || echo 'Error: Failed to remove existing ~/.vimrc'
[[ -d ~/.vim ]] || mkdir ~/.vim || echo 'Error: Failed to create ~/.vim'

cp -f ./.vim/vimrc ~/.vim
chmod 550 ~/.vim/vimrc

###
### Now install ~/bin scripts.
cd ./bin
[[ -d ~/bin ]] || mkdir ~/bin || echo 'Error: Failed to create ~/bin'
chmod 755 ~/bin

BIN_SCRIPTS='
    installHome
    path
    pathTrim
    pushHome
    pushHome
    realPath
    spin
    whence
'

# Scripts
cp -f $BIN_SCRIPTS ~/bin
(cd ~/bin; chmod 555 $BIN_SCRIPTS; chmod 550 pushHome installHome)

# Setup Symlinks for MATLAB
# Find where MATLAB is installed:
if [[ -d ~/opt/MATLAB ]]
then
    MATLAB_INSTALL_DIR=~/opt/MATLAB
elif [[ -d ~/local/MATLAB ]]
then
    MATLAB_INSTALL_DIR=~/local/MATLAB
elif [[ -d /opt/MATLAB ]]
then
    MATLAB_INSTALL_DIR=/usr/local/MATLAB
elif [[ -d /usr/local/MATLAB ]]
then
    MATLAB_INSTALL_DIR=/usr/local/MATLAB
else
    MATLAB_INSTALL_DIR=""
fi

if [[ -d $MATLAB_INSTALL_DIR ]]
then
    #Find latest version of MATLAB and create symlinks
    MATLAB_BIN=$MATLAB_INSTALL_DIR/$(for Rdir in $MATLAB_INSTALL_DIR/R*
                                     do
                                         echo ${Rdir##*/}
                                     done | sort | tail -1)/bin
    rm ~/bin/{matlab,mex}
    ln -s $MATLAB_BIN/{matlab,mex} ~/bin 2> /dev/null
fi

cd ..   # Get out of bin

###
### Now install tracked directories into ~/info.
###   Good only for flat directory structures,
###   unless we manually fix subdirectory permisions 
###   as we do for info/Others.
cd ./info
[[ -d ~/info ]] || mkdir ~/info
chmod 750 ~/info

Info_Dirs='
    Others
    Preferences
    Web
'
for Info_Dir in $Info_Dirs
do
    [[ -d ~/info/$Info_Dir ]] || mkdir ~/info/$Info_Dir
    chmod -R u+rwx ~/info/$Info_Dir
    cp -Rf $Info_Dir ~/info
    chmod -R go-wx ~/info/$Info_Dir
    chmod -R g+r ~/info/$Info_Dir
    chmod g+x ~/info/$Info_Dir
    chmod u-wx ~/info/$Info_Dir/*
done
# Manually fix sub-directories for ~/info/Others
chmod u-wx $(ls -dA ~/info/Others/.* | sed '/\/\.\{1,2\}$/d')
chmod u+wx ~/info/Others/bin
chmod g+x ~/info/Others/bin
chmod ug+x-w ~/info/Others/bin/*

cd ..   # Get out of info
