#!/bin/bash
#
# Trims off duplicate entries and non-existant directories
# in colen separated lists.  Useful when $HOME is shared
# between many systems.  Also when .bash_profile gets resourced.
#
# Usage: pathTrim colen:separated:list
#
# Written by Geoffrey Scheller 
#
unset Fields Path
shopt -s extglob

# Remove redundant /'s and :'s with sed, if we can find it.
# Usually these happen when shell variables evaluate to null.
SED=''
for Dir in /bin /usr/bin /usr/local/bin
do
   [[ -x $Dir/sed ]] && SED=$Dir/sed && break
done
if [[ -n $SED ]]; then
   Path=$(echo $* | $SED -e 's|/\+|/|g
                             s|:\+|:|g')
else
   Path="$*"
fi

OLDIFS=$IFS; IFS=':'
for Dir in $Path
do
    Dir=${Dir%%+(/)}                    # Remove trailing /'s
    [[ -d "$Dir" ]] || continue         # Why look if not there?
    for Field in "${Fields[@]}"         # Search for duplicates
    do
        [[ $Field == $Dir ]] && continue 2
    done
    Fields+=($Dir)                      # Append to end of array
done
IFS=$OLDIFS

Path=''
for Field in "${Fields[@]}"             # Create PATH string from array
do
    Path+=${Field}:
done
echo ${Path%:}                          # Remove final :
