name: pythag-triples
version: 0.4.2
synopsis: Pythagorean triple CLI generation program
category: Example
author: Geoffrey Scheller
maintainer: Geoffrey Scheller <geoffrey@scheller.com>
copyright: (c) 2016-2022 Geoffrey R Scheller
license: BSD3
license-file: LICENSE
extra-source-files:
  - README.md
  - CHANGELOG.md

dependencies:
  - base >= 4.3 && < 5
  - split

library:
  source-dirs: src
  exposed-modules: PythagTriples
  ghc-options: -Wall

executables:
  pythagTriples:
    source-dirs: drivers
    main: pythagTriples.hs
    ghc-options: -Wall -dynamic -threaded -rtsopts -with-rtsopts=-N
    dependencies: pythag-triples

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    ghc-options: -Wall -dynamic -threaded -rtsopts -with-rtsopts=-N
    dependencies: pythag-triples
